### ISSUE TITLE
Package structure requires newer Python

### ISSUE THREAD

**Issue by j-woz** [nexpy/nxvalidate#20]
When setting up GitHub workflows for nxvalidate, the installation fails for the default Python 3.10 but works with Python 3.11 , apparently due to version-specific handling of pyproject.toml .

**Comment by rayosborn** [comment]
I am able to install nxvalidate in Python 3.10 without any problem. Apparently, Python 3.11 added `tomllib` library into the main distribution, but that should be handled by the `requires-python = ">=3.8"` line in pyproject.toml. Could the problem be with the version of Github Actions being invoked or with the setup of the Python versions?

**Comment by j-woz** [comment]
I am also able to install it locally or with GitHub's action setup-python- the issue only seems to occur when not using action setup-python.  We just won't do that.  See here: 
https://github.com/j-woz/nxvalidate/actions/runs/11167536533/job/31043958378
