### ISSUE TITLE
NXenvironment is an invalid class in NXsample

### ISSUE THREAD

**Issue by jkotan** [nexpy/nxvalidate#7]
I get the following error
```
NXenvironment is an invalid class in NXsample
```
However I think `temperature_env:NXenvironment` is a valid class in NXsample

**Comment by rayosborn** [comment]
I have just released v0.2.0b1. Please check to see if this is still a bug.

**Comment by jkotan** [comment]
This bug is not there when I use the last locally installed  base_case definitions with -d option. So I will close it
