### ISSUE TITLE
NXdata is an invalid class in NXsample

### ISSUE THREAD

**Issue by jkotan** [nexpy/nxvalidate#9]
I get
```
        NXdata: /scan/sample_environment/data
                NXdata is an invalid class in NXsample
```
However in the documentation it is written that NXdata can be placed in any location

**Comment by rayosborn** [comment]
I have just released v0.2.0b1. Please check if this has been fixed or not.

**Comment by jkotan** [comment]
The bug is also in v0.2.0b1

**Comment by jkotan** [comment]
I prefer to create NXdata only below NXentry. However, e.g. people from HZM very like to create groups in different places e.g. below NXsample ( due to
https://github.com/nexusformat/definitions/blob/9059815e131dd308677d01da793b63f9d214dbb3/manual/source/design.rst?plain=1#L479-L520 )
